AWSTemplateFormatVersion: 2010-09-09
Description: |
Resources:
  ASGVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.10.0.0/16
      EnableDnsSupport: false
      EnableDnsHostnames: false
      Tags:
        - Key: Name
        - Value: ASG

  ASGPublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      # VpcId: !Ref ASGVpc
